### ISSUE TITLE
rewrite as well for https

### ISSUE THREAD

**Issue by kcassam** [h5bp/server-configs-apache#78] opened 2015-09-24 09:36 UTC
https://github.com/h5bp/server-configs-apache/blob/master/src/rewrites/rewrite_www.conf

Why exclude https ? should work the same way

**Comment by XhmikosR** [comment] 2016-02-06 08:33
Duplicate of https://github.com/h5bp/server-configs-apache/issues/52

**Closed** 2017-09-01 08:24 UTC
