### ISSUE TITLE
Rewrite not removing www while forcing https

### ISSUE THREAD

**Issue by gracedigital** [h5bp/server-configs-apache#91] opened 2016-01-05 17:28 UTC
Using the latest .htaccess file with Apache 2.4.12, PHP 5.5.22 on linux it was not supressing the "www" subdomain, e.g. https://www.mydomain.com.   I tried accessing via HTTP & HTTPS but it didn't work.  This is the code that ended up working for me starting on line 381...

RewriteEngine On
RewriteCond %{HTTP_HOST} ^www.
RewriteCond %{HTTPS}s ^on(s)|off
RewriteCond http%1://%{HTTP_HOST} ^(https?://)(www.)?(.+)$
RewriteRule ^ %1%3%{REQUEST_URI} [R=301,L]

[phpinfo.pdf](https://github.com/h5bp/server-configs-apache/files/78736/phpinfo.pdf)

**Comment by XhmikosR** [comment] 2016-02-06 08:33
Duplicate of https://github.com/h5bp/server-configs-apache/issues/52

**Comment by micr0lab** [comment] 2017-05-02 03:08
@XhmikosR  Ok, the question / the topic is a duplicate, but this solution is actually the right one to avoid multiple redirections.

According to https://www.linksspy.com/seo-tools/free-seo-ssl-scan/ , I previously had http://www.mydom.com => http://mydom.com => https://mydom.com when I simply uncommented the "Forcing `https://`" and "`Option 1` (no `www.`)" parts of the `.htacess` file.

The above code, in place of "Option 1` (no `www.`)", did the trick, and avoid multiple redirections

**Comment by XhmikosR** [comment] 2017-05-02 04:49
There are numerous issues for this specific one.

**Closed** 2017-09-01 08:25 UTC
